# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='fav',
            field=models.NullBooleanField(default=False),
        ),
    ]
